<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_LoginSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bca5287d-907f-43d6-b451-cfad398ffd6d</testSuiteGuid>
   <testCaseLink>
      <guid>61626038-3250-4f3c-a4fd-d52612cec85a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>973d1188-566a-4604-9bf7-ac37171b327d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>973d1188-566a-4604-9bf7-ac37171b327d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>fafaf2f8-19ab-44fa-a038-656717373138</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>973d1188-566a-4604-9bf7-ac37171b327d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>92ceac49-f9be-40da-ba71-6e00442aa59b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
